server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${fia-db-host:mongodb://root:example@localhost:27017/admin}
  task:
    scheduling:
      time:
        coingecko-fetch: "0/10 * * * * *"
        calc-day-avg: "0 0/1 * * * *"
  kafka:
    producer:
      bootstrap-servers: ${fia-kafka-host:localhost:9093}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${fia-kafka-host:localhost:9093}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      group-id: test
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 5
      fetch-max-wait: 60
    topics:
      coin-price: fia-coin-price
springdoc:
  swagger-ui:
    path: swagger-ui.html
client:
  coingecko:
    host: "https://api.coingecko.com/api/v3"
    coin-ids: "bitcoin,tether,ethereum,heco-peg-bnb,usd-coin,binance-peg-xrp,cardano,matic-network,binance-peg-dogecoin,binance-peg-litecoin"

